repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.4.0
  hooks:
  - id: reorder-python-imports
    language_version: python3
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length, "79"]
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
    language_version: python3
  - id: end-of-file-fixer
    language_version: python3
  - id: debug-statements
    language_version: python3
- repo: https://github.com/asottile/pyupgrade
  rev: v1.12.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
    language_version: python3
- repo: local
  hooks:
  - id: system-flake8
    name: flake8
    entry: python3 -m flake8.__main__
    files: \.py$
    language: system
